### ISSUE TITLE
Can we chat?

### ISSUE THREAD

**Issue by ryanrussell** [adaojunior/md#13]
Sorry to muddy up your issues, I don't think you have messaging enabled on your git account.

Are you interesting in contracting? I'm wanting to build some stuff in angular2 and came across your git repos.

I'd love to chat.

Ryan

**Comment by adaojunior** [comment]
Sorry, I haven't seen your message haha.

Are you on the dartlang slack ? You can send me a message there, you can also send me a message at `itsjunnior@gmail.com`.
